### PR TITLE
Task/improve cgi return status

### LINKED ISSUE #124: Wrong CGI return status
We only return error response from a CGI script when the CGI binary doesn't have execution permissions. If the binary is malformed or if any of the other system calls we do after the fork fail we will leave the client hanging without any response.

### PR DESCRIPTION
**Pull request by gbudau**
resolves #124

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -3,7 +3,7 @@ CXX ?= clang++
 DBG ?=
 export CXX
 export DBG
-CXXFLAGS = -Wall -Werror -Wextra -std=c++98 -O3 -g3
+CXXFLAGS = -Wall -Werror -Wextra -std=c++98 -g3
```
Comment (gbudau) [inline Makefile:6]: I removed the `-O3` flag while debugging. This flag is brilliant :heart:, and it improves the running speed by a lot. But using it while developing it also means more compiling time and possibly inaccurate debugging.

File: srcs/app/CGI/CgiHandler.cpp [hunk 2]
```diff
@@ -26,21 +37,217 @@ ssize_t	CgiHandler::SendCgiOutput() {
...
+		ParseHeaders_();
+		if (cgi_complete_ && !headers_parsing_complete_) {
+			throw std::runtime_error("Invalid header");
+		}
+	}
+	catch (const std::exception &) {
+		fd_sets_->removeFd(cgi_info_.cgi_output_fd);
+		SetErrorResponse_(500);
+		if (!cgi_complete_) {
+			kill(cgi_info_.pid, SIGTERM);
```
Comment (Damrod) [inline srcs/app/CGI/CgiHandler.cpp:69]: Why SIGTERM?
I'm a fan of SIGKILL, but maybe I don't have any particular reason other than the fact that the child could not ignore it or otherwise handle it.

Comment (gbudau) [reply srcs/app/CGI/CgiHandler.cpp:69]: Agree. I think SIGKILL would be better in this case.

File: srcs/app/CGI/CgiHandler.cpp [hunk 3]
```diff
@@ -26,21 +37,217 @@ ssize_t	CgiHandler::SendCgiOutput() {
...
+		fd_sets_->removeFd(cgi_info_.cgi_output_fd);
+		SetErrorResponse_(500);
+		if (!cgi_complete_) {
+			kill(cgi_info_.pid, SIGKILL);
+		}
+		cgi_complete_ = true;
+	}
+}
+
+void	CgiHandler::ParseHeaders_() {
```
Comment (Damrod) [inline srcs/app/CGI/CgiHandler.cpp:75]: As you know, there is a lot of common code between this one and srcs/app/http/HttpRequest.cpp:243 void	HttpRequest::ParseHeaders_(const std::string &raw_request);
Did you see it to be too complicated, timeconsuming or generally bothersome to factor it out?

File: srcs/app/CGI/CgiInfo.cpp [hunk 4]
```diff
@@ -0,0 +1,12 @@
+#include <CgiInfo.hpp>
+
+CgiInfo::CgiInfo() : pid(-1), cgi_output_fd(-1) {}
+
+CgiInfo::CgiInfo(const pid_t &new_pid,
```
Comment (Damrod) [inline srcs/app/CGI/CgiInfo.cpp:5]: Why do you believe it's useful to pass these non aggregate values (new_pid and new_cgi_output_fd) by reference?

File: srcs/incs/CgiInfo.hpp [hunk 5]
```diff
@@ -0,0 +1,22 @@
+#ifndef SRCS_INCS_CGIINFO_HPP_
+#define SRCS_INCS_CGIINFO_HPP_
+#include <sys/types.h>
+#include <stdint.h>
+#include <map>
+#include <string>
+
+struct CgiInfo {
```
Comment (Damrod) [inline srcs/incs/CgiInfo.hpp:8]: I really like this class! Thank you!

File: srcs/app/CGI/CgiHandler.cpp [hunk 6]
```diff
@@ -1,22 +1,33 @@
...
-CgiHandler::CgiHandler(int socket, int cgi_output)
-	: socket_(socket), cgi_output_(cgi_output), cgi_complete_(false) {}
+CgiHandler::CgiHandler(FDsets *fd_sets, int socket, const CgiInfo &cgi_info)
+	: fd_sets_(fd_sets), socket_(socket), cgi_info_(cgi_info),
+	cgi_complete_(false), headers_parsing_complete_(false), status_(200) {
+	fd_sets_->addToReadSet(cgi_info_.cgi_output_fd);
+}
 
 CgiHandler::~CgiHandler() {
+	fd_sets_->removeFd(socket_);
```
Comment (Damrod) [inline srcs/app/CGI/CgiHandler.cpp:10]: It looks very clean after you moved these operations on the fd_sets to the constructor and destructor of this class! Thanks!

**Review by Damrod — APPROVED** [review]
Looks great! Thank you!

File: srcs/app/CGI/CgiHandler.cpp (hunk 3 above)
Comment (gbudau) [reply srcs/app/CGI/CgiHandler.cpp:75]: Thanks for pointing this out.

We could refactor the duplicate functionality of parsing HTTP headers to a new class/component. I decided not to do it in this PR because I thought it was time-consuming.

 I will add a new issue to track this.

File: srcs/app/CGI/CgiInfo.cpp (hunk 4 above)
Comment (gbudau) [reply srcs/app/CGI/CgiInfo.cpp]: I've changed it. I was used to passing the parameters by reference in the constructors.

File: srcs/incs/CgiInfo.hpp (hunk 5 above)
Comment (gbudau) [reply srcs/incs/CgiInfo.hpp:8]: Thank you!

File: srcs/app/CGI/CgiHandler.cpp (hunk 6 above)
Comment (gbudau) [reply srcs/app/CGI/CgiHandler.cpp:10]: Thank you!

File: srcs/app/CGI/CgiHandler.cpp (hunk 3 above)
Comment (Damrod) [reply srcs/app/CGI/CgiHandler.cpp:75]: I have an opinion about this, that I would like to share.

We're programming in cpp, and we're trying to do the most object oriented code we can. Object orientation is programming paradigm that bundles code to data, and very often it is very much convenient, makes code easily extensible, clear ownership, and so on.

But I don't think it's a magic wand that solves every programming problem. In this instance, I think an acceptable solution would be to separate code from data, make the methods in the class that parses http headers static, and pass whatever data it needs on the arguments of the function itself, C style. Like that we could easily use it from inside either of the classes that need it, and I think the work footprint would be much smaller.

What do you think about this solution?

Comment (gbudau) [reply srcs/app/CGI/CgiHandler.cpp:75]: Sounds good to me. I'll give it a try.

Comment (Damrod) [reply srcs/app/CGI/CgiHandler.cpp:75]: If you want I can do it myself, but not on the schedule we were thinking about (before next Sunday). I could probably do most of it on Saturday, as I travel.

Comment (gbudau) [reply srcs/app/CGI/CgiHandler.cpp:75]: I'll do it because I want to improve at refactoring and OOP. Thank you!

File: srcs/test/integration/misc_test.py [hunk 7]
```diff
@@ -1,7 +1,39 @@
...
 def test_method_not_implemented_501():
     url = 'http://localhost:8080/'
     response = requests.options(url)
     assert response.status_code == 501
+
+def test_invalid_cgi_binary_500():
+    url = 'http://localhost:8094/info.php'
+    response = requests.get(url)
+    assert response.status_code == 500
+
```
Comment (vdedios) [inline srcs/test/integration/misc_test.py:14]: Great you added some tests but I'd made a custom `cgi_test` file (I understand you've placed them here in order to gather all error test cases)

File: srcs/server/Connection.cpp [hunk 8]
```diff
@@ -39,11 +39,14 @@ SendResponseStatus::Type	Connection::SendResponse() {
 		response_ = response_factory_->Response();
 		raw_response_ = response_->Content();
 	}
-	ssize_t nbytes = send(socket_, raw_response_.c_str(), raw_response_.size(), 0);
-	if (nbytes <= 0) {
-		return SendResponseStatus::kFail;
+	if (!response_->IsCgi()) {
```
Comment (vdedios) [inline srcs/server/Connection.cpp:42]: I understand you make this to send CGI headers through the cgi handler rather than here, right?

**Review by vdedios — APPROVED** [review]
Great  addition, just some comments to understand it better. Thanks :)

File: srcs/server/Connection.cpp (hunk 8 above)
Comment (gbudau) [reply srcs/server/Connection.cpp:42]: Yes, that's it :+1:

**Comment by gbudau** [comment]
Thank you! :tada:
